#!/usr/bin/env bash
Local Area Network (LAN)
A LAN is used to connect computers and devices within a limited geographical area, such as a home, office, or building.
Wide Area Network (WAN)
A WAN is used to connect geographically distant locations, like the Holberton HQ office and the Holberton-Gandi space.
