#!/usr/bin/env bash
# This script pings an IP address 5 times to check its network availability

# Check if an argument is passed
if [ "$#" -ne 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Ping the provided IP address 5 times
ping -c 5 "$1"
