#!/bin/bash
# Get the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f 4-to_infinity_and_beyond)

# Check if the PID was found
if [ -n "$pid" ]; then
  kill "$pid"  # Terminate the process
  echo "Terminated"
else
  echo "Process not found"
fi
