#!/usr/bin/env bash
# This script displays "Best School" 10 times. For the 9th iteration, "Hi" is displayed after "Best School"

counter=1
while [ $counter -le 10 ]
do
  if [ $counter -eq 9 ]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  ((counter++))
done
