#!/usr/bin/env bash
# This script displays hours from 0 to 12 and minutes from 1 to 59

hour=0
while [ $hour -le 12 ]
do
  echo "Hour: $hour"  # Display the hour once for each hour
  minute=1
  while [ $minute -le 59 ]
  do
    echo $minute  # Display the minute
    ((minute++))   # Increment the minute
  done
  ((hour++))       # Increment the hour
done
