#!/bin/bash
# This script displays hours from 0 to 12 and minutes from 1 to 59

hour=0
while [ $hour -le 12 ]
do
  minute=1
  while [ $minute -le 59 ]
  do
    echo "Hour: $hour"
    echo $minute
    ((minute++))
  done
  ((hour++))
done
