#!/usr/bin/env bash

# Initialize the hour
hour=0

# Loop through 24 hours (0 to 23)
while [ $hour -lt 24 ]
do
  # Display the hour
  echo "Hour: $hour"
  
  # Loop through 60 minutes (0 to 59)
  minute=0
  while [ $minute -lt 60 ]
  do
    # Display the minute
    echo $minute
    ((minute++))  # Increment minute
  done
  
  # Increment hour
  ((hour++))
done
